// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: provenance-v1.1.0.proto

package v11

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Provenance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BuildDefinition *BuildDefinition       `protobuf:"bytes,1,opt,name=build_definition,json=buildDefinition,proto3" json:"build_definition,omitempty"`
	RunDetails      *RunDetails            `protobuf:"bytes,2,opt,name=run_details,json=runDetails,proto3" json:"run_details,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_provenance_v1_1_0_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v1_1_0_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_provenance_v1_1_0_proto_rawDescGZIP(), []int{0}
}

func (x *Provenance) GetBuildDefinition() *BuildDefinition {
	if x != nil {
		return x.BuildDefinition
	}
	return nil
}

func (x *Provenance) GetRunDetails() *RunDetails {
	if x != nil {
		return x.RunDetails
	}
	return nil
}

type BuildDefinition struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BuildType            string                 `protobuf:"bytes,1,opt,name=build_type,json=buildType,proto3" json:"build_type,omitempty"`
	ExternalParameters   *structpb.Struct       `protobuf:"bytes,2,opt,name=external_parameters,json=externalParameters,proto3" json:"external_parameters,omitempty"`
	InternalParameters   *structpb.Struct       `protobuf:"bytes,3,opt,name=internal_parameters,json=internalParameters,proto3" json:"internal_parameters,omitempty"`
	ResolvedDependencies []*ResourceDescriptor  `protobuf:"bytes,4,rep,name=resolved_dependencies,json=resolvedDependencies,proto3" json:"resolved_dependencies,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BuildDefinition) Reset() {
	*x = BuildDefinition{}
	mi := &file_provenance_v1_1_0_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildDefinition) ProtoMessage() {}

func (x *BuildDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v1_1_0_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildDefinition.ProtoReflect.Descriptor instead.
func (*BuildDefinition) Descriptor() ([]byte, []int) {
	return file_provenance_v1_1_0_proto_rawDescGZIP(), []int{1}
}

func (x *BuildDefinition) GetBuildType() string {
	if x != nil {
		return x.BuildType
	}
	return ""
}

func (x *BuildDefinition) GetExternalParameters() *structpb.Struct {
	if x != nil {
		return x.ExternalParameters
	}
	return nil
}

func (x *BuildDefinition) GetInternalParameters() *structpb.Struct {
	if x != nil {
		return x.InternalParameters
	}
	return nil
}

func (x *BuildDefinition) GetResolvedDependencies() []*ResourceDescriptor {
	if x != nil {
		return x.ResolvedDependencies
	}
	return nil
}

type ResourceDescriptor struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	Uri              string                     `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Digest           map[string]string          `protobuf:"bytes,2,rep,name=digest,proto3" json:"digest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Name             string                     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DownloadLocation string                     `protobuf:"bytes,4,opt,name=download_location,json=downloadLocation,proto3" json:"download_location,omitempty"`
	MediaType        string                     `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Content          []byte                     `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Annotations      map[string]*structpb.Value `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceDescriptor) Reset() {
	*x = ResourceDescriptor{}
	mi := &file_provenance_v1_1_0_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDescriptor) ProtoMessage() {}

func (x *ResourceDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v1_1_0_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDescriptor.ProtoReflect.Descriptor instead.
func (*ResourceDescriptor) Descriptor() ([]byte, []int) {
	return file_provenance_v1_1_0_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceDescriptor) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ResourceDescriptor) GetDigest() map[string]string {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *ResourceDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceDescriptor) GetDownloadLocation() string {
	if x != nil {
		return x.DownloadLocation
	}
	return ""
}

func (x *ResourceDescriptor) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ResourceDescriptor) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ResourceDescriptor) GetAnnotations() map[string]*structpb.Value {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type RunDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builder       *Builder               `protobuf:"bytes,1,opt,name=builder,proto3" json:"builder,omitempty"`
	Metadata      *BuildMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Byproducts    []*ResourceDescriptor  `protobuf:"bytes,3,rep,name=byproducts,proto3" json:"byproducts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunDetails) Reset() {
	*x = RunDetails{}
	mi := &file_provenance_v1_1_0_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDetails) ProtoMessage() {}

func (x *RunDetails) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v1_1_0_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDetails.ProtoReflect.Descriptor instead.
func (*RunDetails) Descriptor() ([]byte, []int) {
	return file_provenance_v1_1_0_proto_rawDescGZIP(), []int{3}
}

func (x *RunDetails) GetBuilder() *Builder {
	if x != nil {
		return x.Builder
	}
	return nil
}

func (x *RunDetails) GetMetadata() *BuildMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RunDetails) GetByproducts() []*ResourceDescriptor {
	if x != nil {
		return x.Byproducts
	}
	return nil
}

type Builder struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version             map[string]string      `protobuf:"bytes,2,rep,name=version,proto3" json:"version,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BuilderDependencies []*ResourceDescriptor  `protobuf:"bytes,3,rep,name=builder_dependencies,json=builderDependencies,proto3" json:"builder_dependencies,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Builder) Reset() {
	*x = Builder{}
	mi := &file_provenance_v1_1_0_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Builder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Builder) ProtoMessage() {}

func (x *Builder) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v1_1_0_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Builder.ProtoReflect.Descriptor instead.
func (*Builder) Descriptor() ([]byte, []int) {
	return file_provenance_v1_1_0_proto_rawDescGZIP(), []int{4}
}

func (x *Builder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Builder) GetVersion() map[string]string {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *Builder) GetBuilderDependencies() []*ResourceDescriptor {
	if x != nil {
		return x.BuilderDependencies
	}
	return nil
}

type BuildMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	StartedOn     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_on,json=startedOn,proto3" json:"started_on,omitempty"`
	FinishedOn    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=finished_on,json=finishedOn,proto3" json:"finished_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildMetadata) Reset() {
	*x = BuildMetadata{}
	mi := &file_provenance_v1_1_0_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildMetadata) ProtoMessage() {}

func (x *BuildMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v1_1_0_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildMetadata.ProtoReflect.Descriptor instead.
func (*BuildMetadata) Descriptor() ([]byte, []int) {
	return file_provenance_v1_1_0_proto_rawDescGZIP(), []int{5}
}

func (x *BuildMetadata) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *BuildMetadata) GetStartedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedOn
	}
	return nil
}

func (x *BuildMetadata) GetFinishedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedOn
	}
	return nil
}

var File_provenance_v1_1_0_proto protoreflect.FileDescriptor

const file_provenance_v1_1_0_proto_rawDesc = "" +
	"\n" +
	"\x17provenance-v1.1.0.proto\x12\bslsa.v11\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x01\n" +
	"\n" +
	"Provenance\x12D\n" +
	"\x10build_definition\x18\x01 \x01(\v2\x19.slsa.v11.BuildDefinitionR\x0fbuildDefinition\x125\n" +
	"\vrun_details\x18\x02 \x01(\v2\x14.slsa.v11.RunDetailsR\n" +
	"runDetails\"\x97\x02\n" +
	"\x0fBuildDefinition\x12\x1d\n" +
	"\n" +
	"build_type\x18\x01 \x01(\tR\tbuildType\x12H\n" +
	"\x13external_parameters\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x12externalParameters\x12H\n" +
	"\x13internal_parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x12internalParameters\x12Q\n" +
	"\x15resolved_dependencies\x18\x04 \x03(\v2\x1c.slsa.v11.ResourceDescriptorR\x14resolvedDependencies\"\xc6\x03\n" +
	"\x12ResourceDescriptor\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12@\n" +
	"\x06digest\x18\x02 \x03(\v2(.slsa.v11.ResourceDescriptor.DigestEntryR\x06digest\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12+\n" +
	"\x11download_location\x18\x04 \x01(\tR\x10downloadLocation\x12\x1d\n" +
	"\n" +
	"media_type\x18\x05 \x01(\tR\tmediaType\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\x12O\n" +
	"\vannotations\x18\a \x03(\v2-.slsa.v11.ResourceDescriptor.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vDigestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aV\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xac\x01\n" +
	"\n" +
	"RunDetails\x12+\n" +
	"\abuilder\x18\x01 \x01(\v2\x11.slsa.v11.BuilderR\abuilder\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.slsa.v11.BuildMetadataR\bmetadata\x12<\n" +
	"\n" +
	"byproducts\x18\x03 \x03(\v2\x1c.slsa.v11.ResourceDescriptorR\n" +
	"byproducts\"\xe0\x01\n" +
	"\aBuilder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\aversion\x18\x02 \x03(\v2\x1e.slsa.v11.Builder.VersionEntryR\aversion\x12O\n" +
	"\x14builder_dependencies\x18\x03 \x03(\v2\x1c.slsa.v11.ResourceDescriptorR\x13builderDependencies\x1a:\n" +
	"\fVersionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\rBuildMetadata\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x129\n" +
	"\n" +
	"started_on\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedOn\x12;\n" +
	"\vfinished_on\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedOnB\xae\x01\n" +
	"\fcom.slsa.v11B\x13ProvenanceV110ProtoP\x01ZHgithub.com/carabiner-dev/ampel/pkg/formats/predicate/slsa/provenance/v11\xa2\x02\x03SXX\xaa\x02\bSlsa.V11\xca\x02\bSlsa\\V11\xe2\x02\x14Slsa\\V11\\GPBMetadata\xea\x02\tSlsa::V11b\x06proto3"

var (
	file_provenance_v1_1_0_proto_rawDescOnce sync.Once
	file_provenance_v1_1_0_proto_rawDescData []byte
)

func file_provenance_v1_1_0_proto_rawDescGZIP() []byte {
	file_provenance_v1_1_0_proto_rawDescOnce.Do(func() {
		file_provenance_v1_1_0_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provenance_v1_1_0_proto_rawDesc), len(file_provenance_v1_1_0_proto_rawDesc)))
	})
	return file_provenance_v1_1_0_proto_rawDescData
}

var file_provenance_v1_1_0_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_provenance_v1_1_0_proto_goTypes = []any{
	(*Provenance)(nil),            // 0: slsa.v11.Provenance
	(*BuildDefinition)(nil),       // 1: slsa.v11.BuildDefinition
	(*ResourceDescriptor)(nil),    // 2: slsa.v11.ResourceDescriptor
	(*RunDetails)(nil),            // 3: slsa.v11.RunDetails
	(*Builder)(nil),               // 4: slsa.v11.Builder
	(*BuildMetadata)(nil),         // 5: slsa.v11.BuildMetadata
	nil,                           // 6: slsa.v11.ResourceDescriptor.DigestEntry
	nil,                           // 7: slsa.v11.ResourceDescriptor.AnnotationsEntry
	nil,                           // 8: slsa.v11.Builder.VersionEntry
	(*structpb.Struct)(nil),       // 9: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*structpb.Value)(nil),        // 11: google.protobuf.Value
}
var file_provenance_v1_1_0_proto_depIdxs = []int32{
	1,  // 0: slsa.v11.Provenance.build_definition:type_name -> slsa.v11.BuildDefinition
	3,  // 1: slsa.v11.Provenance.run_details:type_name -> slsa.v11.RunDetails
	9,  // 2: slsa.v11.BuildDefinition.external_parameters:type_name -> google.protobuf.Struct
	9,  // 3: slsa.v11.BuildDefinition.internal_parameters:type_name -> google.protobuf.Struct
	2,  // 4: slsa.v11.BuildDefinition.resolved_dependencies:type_name -> slsa.v11.ResourceDescriptor
	6,  // 5: slsa.v11.ResourceDescriptor.digest:type_name -> slsa.v11.ResourceDescriptor.DigestEntry
	7,  // 6: slsa.v11.ResourceDescriptor.annotations:type_name -> slsa.v11.ResourceDescriptor.AnnotationsEntry
	4,  // 7: slsa.v11.RunDetails.builder:type_name -> slsa.v11.Builder
	5,  // 8: slsa.v11.RunDetails.metadata:type_name -> slsa.v11.BuildMetadata
	2,  // 9: slsa.v11.RunDetails.byproducts:type_name -> slsa.v11.ResourceDescriptor
	8,  // 10: slsa.v11.Builder.version:type_name -> slsa.v11.Builder.VersionEntry
	2,  // 11: slsa.v11.Builder.builder_dependencies:type_name -> slsa.v11.ResourceDescriptor
	10, // 12: slsa.v11.BuildMetadata.started_on:type_name -> google.protobuf.Timestamp
	10, // 13: slsa.v11.BuildMetadata.finished_on:type_name -> google.protobuf.Timestamp
	11, // 14: slsa.v11.ResourceDescriptor.AnnotationsEntry.value:type_name -> google.protobuf.Value
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_provenance_v1_1_0_proto_init() }
func file_provenance_v1_1_0_proto_init() {
	if File_provenance_v1_1_0_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provenance_v1_1_0_proto_rawDesc), len(file_provenance_v1_1_0_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_provenance_v1_1_0_proto_goTypes,
		DependencyIndexes: file_provenance_v1_1_0_proto_depIdxs,
		MessageInfos:      file_provenance_v1_1_0_proto_msgTypes,
	}.Build()
	File_provenance_v1_1_0_proto = out.File
	file_provenance_v1_1_0_proto_goTypes = nil
	file_provenance_v1_1_0_proto_depIdxs = nil
}
