// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: provenance-v0.2.0.proto

package v02

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Provenance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builder       *Builder               `protobuf:"bytes,1,opt,name=builder,proto3" json:"builder,omitempty"`
	BuildType     string                 `protobuf:"bytes,2,opt,name=build_type,json=buildType,proto3" json:"build_type,omitempty"`
	Invocation    *Invocation            `protobuf:"bytes,3,opt,name=invocation,proto3" json:"invocation,omitempty"`
	BuildConfig   *BuildConfig           `protobuf:"bytes,4,opt,name=build_config,json=buildConfig,proto3" json:"build_config,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Materials     []*ResourceDescriptor  `protobuf:"bytes,6,rep,name=materials,proto3" json:"materials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_provenance_v0_2_0_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v0_2_0_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_provenance_v0_2_0_proto_rawDescGZIP(), []int{0}
}

func (x *Provenance) GetBuilder() *Builder {
	if x != nil {
		return x.Builder
	}
	return nil
}

func (x *Provenance) GetBuildType() string {
	if x != nil {
		return x.BuildType
	}
	return ""
}

func (x *Provenance) GetInvocation() *Invocation {
	if x != nil {
		return x.Invocation
	}
	return nil
}

func (x *Provenance) GetBuildConfig() *BuildConfig {
	if x != nil {
		return x.BuildConfig
	}
	return nil
}

func (x *Provenance) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Provenance) GetMaterials() []*ResourceDescriptor {
	if x != nil {
		return x.Materials
	}
	return nil
}

type Invocation struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ConfigSource *ConfigSource          `protobuf:"bytes,1,opt,name=config_source,json=configSource,proto3" json:"config_source,omitempty"`
	// Somewhere we picked a version of this proto where parameters was a list
	// of strings. That is not correct. Parameters is an object
	// Refs:
	//
	//	https://github.com/tektoncd/chains/issues/306
	//	https://slsa.dev/spec/v0.2/provenance
	Parameters    *structpb.Struct `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Environment   *structpb.Struct `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invocation) Reset() {
	*x = Invocation{}
	mi := &file_provenance_v0_2_0_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invocation) ProtoMessage() {}

func (x *Invocation) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v0_2_0_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invocation.ProtoReflect.Descriptor instead.
func (*Invocation) Descriptor() ([]byte, []int) {
	return file_provenance_v0_2_0_proto_rawDescGZIP(), []int{1}
}

func (x *Invocation) GetConfigSource() *ConfigSource {
	if x != nil {
		return x.ConfigSource
	}
	return nil
}

func (x *Invocation) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Invocation) GetEnvironment() *structpb.Struct {
	if x != nil {
		return x.Environment
	}
	return nil
}

type ConfigSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Digest        map[string]string      `protobuf:"bytes,2,rep,name=digest,proto3" json:"digest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EntryPoint    string                 `protobuf:"bytes,3,opt,name=entryPoint,proto3" json:"entryPoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSource) Reset() {
	*x = ConfigSource{}
	mi := &file_provenance_v0_2_0_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSource) ProtoMessage() {}

func (x *ConfigSource) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v0_2_0_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSource.ProtoReflect.Descriptor instead.
func (*ConfigSource) Descriptor() ([]byte, []int) {
	return file_provenance_v0_2_0_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigSource) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ConfigSource) GetDigest() map[string]string {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *ConfigSource) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

type Builder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Builder) Reset() {
	*x = Builder{}
	mi := &file_provenance_v0_2_0_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Builder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Builder) ProtoMessage() {}

func (x *Builder) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v0_2_0_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Builder.ProtoReflect.Descriptor instead.
func (*Builder) Descriptor() ([]byte, []int) {
	return file_provenance_v0_2_0_proto_rawDescGZIP(), []int{3}
}

func (x *Builder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuildConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Steps         []*Step                `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildConfig) Reset() {
	*x = BuildConfig{}
	mi := &file_provenance_v0_2_0_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildConfig) ProtoMessage() {}

func (x *BuildConfig) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v0_2_0_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildConfig.ProtoReflect.Descriptor instead.
func (*BuildConfig) Descriptor() ([]byte, []int) {
	return file_provenance_v0_2_0_proto_rawDescGZIP(), []int{4}
}

func (x *BuildConfig) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BuildConfig) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkingDir    string                 `protobuf:"bytes,1,opt,name=workingDir,proto3" json:"workingDir,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Env           []string               `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_provenance_v0_2_0_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v0_2_0_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_provenance_v0_2_0_proto_rawDescGZIP(), []int{5}
}

func (x *Step) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *Step) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Step) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

type Metadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BuildInvocationID string                 `protobuf:"bytes,1,opt,name=buildInvocationID,proto3" json:"buildInvocationID,omitempty"`
	Completeness      *Metadata_Completeness `protobuf:"bytes,2,opt,name=completeness,proto3" json:"completeness,omitempty"`
	Reproducible      bool                   `protobuf:"varint,3,opt,name=reproducible,proto3" json:"reproducible,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_provenance_v0_2_0_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v0_2_0_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_provenance_v0_2_0_proto_rawDescGZIP(), []int{6}
}

func (x *Metadata) GetBuildInvocationID() string {
	if x != nil {
		return x.BuildInvocationID
	}
	return ""
}

func (x *Metadata) GetCompleteness() *Metadata_Completeness {
	if x != nil {
		return x.Completeness
	}
	return nil
}

func (x *Metadata) GetReproducible() bool {
	if x != nil {
		return x.Reproducible
	}
	return false
}

type ResourceDescriptor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uri              string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Digest           map[string]string      `protobuf:"bytes,2,rep,name=digest,proto3" json:"digest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DownloadLocation string                 `protobuf:"bytes,4,opt,name=download_location,json=downloadLocation,proto3" json:"download_location,omitempty"`
	MediaType        string                 `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Content          []byte                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Annotations      *structpb.Struct       `protobuf:"bytes,7,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceDescriptor) Reset() {
	*x = ResourceDescriptor{}
	mi := &file_provenance_v0_2_0_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDescriptor) ProtoMessage() {}

func (x *ResourceDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v0_2_0_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDescriptor.ProtoReflect.Descriptor instead.
func (*ResourceDescriptor) Descriptor() ([]byte, []int) {
	return file_provenance_v0_2_0_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceDescriptor) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ResourceDescriptor) GetDigest() map[string]string {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *ResourceDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceDescriptor) GetDownloadLocation() string {
	if x != nil {
		return x.DownloadLocation
	}
	return ""
}

func (x *ResourceDescriptor) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ResourceDescriptor) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ResourceDescriptor) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type Metadata_Completeness struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    bool                   `protobuf:"varint,1,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Environment   bool                   `protobuf:"varint,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Materials     bool                   `protobuf:"varint,3,opt,name=materials,proto3" json:"materials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata_Completeness) Reset() {
	*x = Metadata_Completeness{}
	mi := &file_provenance_v0_2_0_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata_Completeness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata_Completeness) ProtoMessage() {}

func (x *Metadata_Completeness) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_v0_2_0_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata_Completeness.ProtoReflect.Descriptor instead.
func (*Metadata_Completeness) Descriptor() ([]byte, []int) {
	return file_provenance_v0_2_0_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Metadata_Completeness) GetParameters() bool {
	if x != nil {
		return x.Parameters
	}
	return false
}

func (x *Metadata_Completeness) GetEnvironment() bool {
	if x != nil {
		return x.Environment
	}
	return false
}

func (x *Metadata_Completeness) GetMaterials() bool {
	if x != nil {
		return x.Materials
	}
	return false
}

var File_provenance_v0_2_0_proto protoreflect.FileDescriptor

const file_provenance_v0_2_0_proto_rawDesc = "" +
	"\n" +
	"\x17provenance-v0.2.0.proto\x12\bslsa.v02\x1a\x1cgoogle/protobuf/struct.proto\"\xb4\x02\n" +
	"\n" +
	"Provenance\x12+\n" +
	"\abuilder\x18\x01 \x01(\v2\x11.slsa.v02.BuilderR\abuilder\x12\x1d\n" +
	"\n" +
	"build_type\x18\x02 \x01(\tR\tbuildType\x124\n" +
	"\n" +
	"invocation\x18\x03 \x01(\v2\x14.slsa.v02.InvocationR\n" +
	"invocation\x128\n" +
	"\fbuild_config\x18\x04 \x01(\v2\x15.slsa.v02.BuildConfigR\vbuildConfig\x12.\n" +
	"\bmetadata\x18\x05 \x01(\v2\x12.slsa.v02.MetadataR\bmetadata\x12:\n" +
	"\tmaterials\x18\x06 \x03(\v2\x1c.slsa.v02.ResourceDescriptorR\tmaterials\"\xbd\x01\n" +
	"\n" +
	"Invocation\x12;\n" +
	"\rconfig_source\x18\x01 \x01(\v2\x16.slsa.v02.ConfigSourceR\fconfigSource\x127\n" +
	"\n" +
	"parameters\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x129\n" +
	"\venvironment\x18\x03 \x01(\v2\x17.google.protobuf.StructR\venvironment\"\xb7\x01\n" +
	"\fConfigSource\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12:\n" +
	"\x06digest\x18\x02 \x03(\v2\".slsa.v02.ConfigSource.DigestEntryR\x06digest\x12\x1e\n" +
	"\n" +
	"entryPoint\x18\x03 \x01(\tR\n" +
	"entryPoint\x1a9\n" +
	"\vDigestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x19\n" +
	"\aBuilder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\vBuildConfig\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12$\n" +
	"\x05steps\x18\x02 \x03(\v2\x0e.slsa.v02.StepR\x05steps\"R\n" +
	"\x04Step\x12\x1e\n" +
	"\n" +
	"workingDir\x18\x01 \x01(\tR\n" +
	"workingDir\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x10\n" +
	"\x03env\x18\x03 \x03(\tR\x03env\"\x91\x02\n" +
	"\bMetadata\x12,\n" +
	"\x11buildInvocationID\x18\x01 \x01(\tR\x11buildInvocationID\x12C\n" +
	"\fcompleteness\x18\x02 \x01(\v2\x1f.slsa.v02.Metadata.CompletenessR\fcompleteness\x12\"\n" +
	"\freproducible\x18\x03 \x01(\bR\freproducible\x1an\n" +
	"\fCompleteness\x12\x1e\n" +
	"\n" +
	"parameters\x18\x01 \x01(\bR\n" +
	"parameters\x12 \n" +
	"\venvironment\x18\x02 \x01(\bR\venvironment\x12\x1c\n" +
	"\tmaterials\x18\x03 \x01(\bR\tmaterials\"\xd8\x02\n" +
	"\x12ResourceDescriptor\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12@\n" +
	"\x06digest\x18\x02 \x03(\v2(.slsa.v02.ResourceDescriptor.DigestEntryR\x06digest\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12+\n" +
	"\x11download_location\x18\x04 \x01(\tR\x10downloadLocation\x12\x1d\n" +
	"\n" +
	"media_type\x18\x05 \x01(\tR\tmediaType\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\x129\n" +
	"\vannotations\x18\a \x01(\v2\x17.google.protobuf.StructR\vannotations\x1a9\n" +
	"\vDigestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xae\x01\n" +
	"\fcom.slsa.v02B\x13ProvenanceV020ProtoP\x01ZHgithub.com/carabiner-dev/ampel/pkg/formats/predicate/slsa/provenance/v02\xa2\x02\x03SXX\xaa\x02\bSlsa.V02\xca\x02\bSlsa\\V02\xe2\x02\x14Slsa\\V02\\GPBMetadata\xea\x02\tSlsa::V02b\x06proto3"

var (
	file_provenance_v0_2_0_proto_rawDescOnce sync.Once
	file_provenance_v0_2_0_proto_rawDescData []byte
)

func file_provenance_v0_2_0_proto_rawDescGZIP() []byte {
	file_provenance_v0_2_0_proto_rawDescOnce.Do(func() {
		file_provenance_v0_2_0_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provenance_v0_2_0_proto_rawDesc), len(file_provenance_v0_2_0_proto_rawDesc)))
	})
	return file_provenance_v0_2_0_proto_rawDescData
}

var file_provenance_v0_2_0_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_provenance_v0_2_0_proto_goTypes = []any{
	(*Provenance)(nil),            // 0: slsa.v02.Provenance
	(*Invocation)(nil),            // 1: slsa.v02.Invocation
	(*ConfigSource)(nil),          // 2: slsa.v02.ConfigSource
	(*Builder)(nil),               // 3: slsa.v02.Builder
	(*BuildConfig)(nil),           // 4: slsa.v02.BuildConfig
	(*Step)(nil),                  // 5: slsa.v02.Step
	(*Metadata)(nil),              // 6: slsa.v02.Metadata
	(*ResourceDescriptor)(nil),    // 7: slsa.v02.ResourceDescriptor
	nil,                           // 8: slsa.v02.ConfigSource.DigestEntry
	(*Metadata_Completeness)(nil), // 9: slsa.v02.Metadata.Completeness
	nil,                           // 10: slsa.v02.ResourceDescriptor.DigestEntry
	(*structpb.Struct)(nil),       // 11: google.protobuf.Struct
}
var file_provenance_v0_2_0_proto_depIdxs = []int32{
	3,  // 0: slsa.v02.Provenance.builder:type_name -> slsa.v02.Builder
	1,  // 1: slsa.v02.Provenance.invocation:type_name -> slsa.v02.Invocation
	4,  // 2: slsa.v02.Provenance.build_config:type_name -> slsa.v02.BuildConfig
	6,  // 3: slsa.v02.Provenance.metadata:type_name -> slsa.v02.Metadata
	7,  // 4: slsa.v02.Provenance.materials:type_name -> slsa.v02.ResourceDescriptor
	2,  // 5: slsa.v02.Invocation.config_source:type_name -> slsa.v02.ConfigSource
	11, // 6: slsa.v02.Invocation.parameters:type_name -> google.protobuf.Struct
	11, // 7: slsa.v02.Invocation.environment:type_name -> google.protobuf.Struct
	8,  // 8: slsa.v02.ConfigSource.digest:type_name -> slsa.v02.ConfigSource.DigestEntry
	5,  // 9: slsa.v02.BuildConfig.steps:type_name -> slsa.v02.Step
	9,  // 10: slsa.v02.Metadata.completeness:type_name -> slsa.v02.Metadata.Completeness
	10, // 11: slsa.v02.ResourceDescriptor.digest:type_name -> slsa.v02.ResourceDescriptor.DigestEntry
	11, // 12: slsa.v02.ResourceDescriptor.annotations:type_name -> google.protobuf.Struct
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_provenance_v0_2_0_proto_init() }
func file_provenance_v0_2_0_proto_init() {
	if File_provenance_v0_2_0_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provenance_v0_2_0_proto_rawDesc), len(file_provenance_v0_2_0_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_provenance_v0_2_0_proto_goTypes,
		DependencyIndexes: file_provenance_v0_2_0_proto_depIdxs,
		MessageInfos:      file_provenance_v0_2_0_proto_msgTypes,
	}.Build()
	File_provenance_v0_2_0_proto = out.File
	file_provenance_v0_2_0_proto_goTypes = nil
	file_provenance_v0_2_0_proto_depIdxs = nil
}
