# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

name: Check Copyright Boilerplates

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  check:
    name: Boilerplate Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        extension:
        - go
        - sh
        - yaml
        - yml
        - html
        - css
        include:
        - extension: go
          language: Go
        - extension: sh
          language: Bash
        - extension: yaml
          language: YAML
        - extension: yml
          language: YAML
        - extension: proto
          language: protobuf

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: chainguard-dev/actions/boilerplate@9978bf17926f53444b5eff45479954d94ec12e32 # v1.6.24
        with:
          boilerplate-directory: "./hack/boilerplates"
          extension: ${{ matrix.extension }}
          language: ${{ matrix.language }}
